CLOCK_TIMEOUT: 1000.0  # 1000mS timeout for external clock locking
INIT_DELAY: 0.2  # 200ms initial delay before transmit

################## 
# SERVER  CONF ###
################## 
SERVER_IP: "192.108.2.30"


ERROR_PORT: "5555"


################## 
#### RF  CONF ####
################## 

FREQ: !!float 920e6
RATE: !!float 250e3


################## 
## RF CHAIN CONF #
################## 

############## GAINS ##############
LOOPBACK_RX_GAIN: 40 #23  # empirical determined
LOOPBACK_TX_GAIN: 60 

REF_RX_GAIN: 40 # SHOULD BE THE SAME AS LOOPBACK RX
BF_TX_GAIN: 72

FREE_TX_GAIN: 0  # no gain to be sure

PILOT_TX_GAIN: 88


############## CHANNELS AND ANTENNAS ##############
# no need to define antenna is this is done manually in the USRP

# Pilot USRP
PILOT_TX_CH: 0
PILOT_TX_ANT: "TX/RX"

# USRPs

LOOPBACK_RX_CH: 1 
LOOPBACK_TX_CH: 1


REF_RX_CH: 0
REF_RX_ANT: "RX2"

PILOT_RX_CH: 1
PILOT_RX_ANT: "TX/RX"

BF_TX_CH: 1
BF_TX_ANT: "TX/RX"

FREE_TX_CH: 0  # as unused, same channel as REF cable
FREE_TX_ANT: "TX/RX"

# TX/RX A:  [not used] Antenna
# RX A:     REF 

# RX B:     50ohm terminated
# TX/RX B:  Antenna

## 1 #### 0 ##
## B #### A ##
##############
##############
##############
##############
##############


################## 
# FRAME SCHEDULE #
################## 

START_TUNE: 3
CAPTURE_TIME: 10  # seconds to capture the data USED FOR BUFFER LENGTH

# Loopback
START_LB: 5
STOP_LB: 15

# PILOT 1
START_P1_TX: 22
STOP_P1_TX: 35

START_P1_RX: 28
STOP_P1_RX: 33

# Pilot 2
START_P2_TX: 42
STOP_P2_TX: 55

START_P2_RX: 47
STOP_P2_RX: 52

# BF
START_BF: 45
STOP_BF: 7200